import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AuthProvider from "./api/auth/Provider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={`${inter.className} custom-scrollbar`}>
          {children}
        </body>
      </html>
    </AuthProvider>
  );
}
